import {Word} from "./word.model";

export const WORDS: Word[] = [
  new Word('nähdään', 'See you'),
  new Word('tervetuloa', 'welcome'),
  new Word('täällä', 'here'),
  new Word('kuinka vanha sinä olet?', 'how old are you?'),
  new Word('puisto', 'park'),
  new Word('loppua', 'end'),
  new Word('kello', 'clock'),
  new Word('muu', 'other'),
  new Word('opiskelija', 'student'),
  new Word('mennä', 'to go'),
  new Word('koti', 'home'),
  new Word('mutta', 'but'),
  new Word('kioski', 'kiosk'),
  new Word('ostaa', 'to buy'),
  new Word('jäätelö', 'ice cream'),
  new Word('maksaa', 'to pay'),
  new Word('säästää', 'to save'),
  new Word('raha', 'money'),
  new Word('sitten', 'then'),
  new Word('istua', 'to sit'),
  new Word('puhua', 'to speak'),
  new Word('naura', 'to laugh'),
  new Word('minkämaalainen', 'from which country'),
  new Word('entä', 'what about'),
  new Word('mistä', 'wherece'),
  new Word('toissapäivänä', 'the day before yesterday')
];
